services:

  backend:
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
    ports:
      - "4005:4000"
    env_file:
      - .env
    networks:
      - custody_global_network


networks:
  custody_global_network:
    external: true


