name: Deploy to demo-server 
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Deploy to demo
      env:
        PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY_2}}
        HOST: 49.13.230.22
        USER: root
      run: |
        echo "$PRIVATE_KEY" > private_key 
        chmod 600 private_key
         ssh -i private_key   -o StrictHostKeyChecking=no  $USER@$HOST  " 
         root@ubuntu-32gb-nbg1-1:~/demo/deploy# cat custody-private-server.sh
         cd /root/demo/custody-private-server
         git pull --recurse-submodules
         cd rox-custody_common-modules/
         git checkout main
         git pull
         cd ..
         docker build -t demo-custody-private-server .
        docker rm -f demo-custody-private-server
        docker run -d -p 4024:3000 --name=demo-custody-private-server --restart=unless-stopped  demo-custody-private-server "
